# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.98.0"
REQUIRED_XCODE_VERSION = "7.3.1"
default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to **TestFlight**"
  lane :beta do |options|
    # Set build number to current date and time
    build_number = Time.new.strftime("%Y.%m.%d.%H.%M")
    ENV["BUILD_NUMBER"] = build_number
    increment_build_number build_number: build_number
    # Beta badge app icon
    badge(dark: false)

    # Certs & Provisioning Profiles
    match(type: "appstore")
    puts "AppStore UDID: "+ENV["sigh_eu.ricardopereira.Screensketch_appstore"]

    # Build
    gym(
      scheme: "Screensketch",
      export_method: "app-store",
      suppress_xcode_output: true,
      xcargs: "APP_PROFILE='#{ENV["sigh_eu.ricardopereira.Screensketch_appstore"]}'",
    )

    # Submit to iTunes Connect
    pilot(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    ) # Skip the distribution of the app to all beta testers

    clean_build_artifacts
  end

  desc "Submit a new Release Build to **AppStore**"
  lane :release do |options|
    # Automatically increment by one
    increment_version_number(
      bump_type: "minor" # Automatically increment minor version number
    )

    # Certs & Provisioning Profiles
    match(type: "appstore")
    puts "AppStore UDID: "+ENV["sigh_eu.ricardopereira.Screensketch_appstore"]

    # Build
    gym(
      scheme: "Screensketch",
      export_method: "app-store",
      suppress_xcode_output: true,
      xcargs: "APP_PROFILE='#{ENV["sigh_eu.ricardopereira.Screensketch_appstore"]}'",
    )

    # Submit to iTunes Connect
    pilot(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    ) # Skip the distribution of the app to all beta testers

    clean_build_artifacts
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
